# Generated by Django 3.0.dev20190712152749 on 2019-07-23 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0004_auto_20190722_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='day',
            field=models.CharField(choices=[('MON', 'Monday'), ('TUES', 'Tuesday'), ('WED', 'Wednesday'), ('THURS', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=5),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='end_time',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='start_time',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, to='one.Student'),
        ),
    ]
