# Generated by Django 3.0.dev20190712152749 on 2019-07-25 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0005_auto_20190723_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='enrollment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meeting',
            name='waitlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='meeting_waitlist', to='one.Student'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='day',
            field=models.CharField(choices=[('Monday', 'MON'), ('Tuesday', 'TUES'), ('Wednesday', 'WED'), ('Thursday', 'THURS'), ('Friday', 'FRI'), ('Saturday', 'SAT'), ('Sunday', 'SUN')], max_length=10),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, related_name='meeting_students', to='one.Student'),
        ),
    ]
