# Generated by Django 3.0.dev20190712152749 on 2019-07-25 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0006_auto_20190725_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='meeting_students', to='one.Student'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='waitlist',
            field=models.ManyToManyField(blank=True, related_name='meeting_waitlist', to='one.Student'),
        ),
    ]
