# Generated by Django 3.0.dev20190712152749 on 2019-07-25 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0007_auto_20190725_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='max',
            field=models.IntegerField(default=15),
        ),
    ]
