# Generated by Django 3.0.dev20190712152749 on 2019-07-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0009_studentuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='meeting_students', to='one.StudentUser'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='waitlist',
            field=models.ManyToManyField(blank=True, related_name='meeting_waitlist', to='one.StudentUser'),
        ),
    ]
