# Generated by Django 3.0.dev20190712152749 on 2019-07-26 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0010_auto_20190726_1907'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
