# Generated by Django 3.0.dev20190712152749 on 2019-07-26 19:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('one', '0011_delete_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentUser',
            new_name='Student',
        ),
    ]
