# Generated by Django 3.0.dev20190712152749 on 2019-07-26 19:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('one', '0012_auto_20190726_1910'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='StudentUser',
        ),
    ]
