# Generated by Django 3.0.dev20190712152749 on 2019-08-25 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0013_auto_20190726_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='students', to='one.StudentUser'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='waitlist',
            field=models.ManyToManyField(blank=True, related_name='waitlist', to='one.StudentUser'),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
