# Generated by Django 3.0.dev20190712152749 on 2019-08-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0014_auto_20190825_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='location',
            field=models.CharField(default='TBD', max_length=200),
        ),
    ]
