# Generated by Django 3.0.dev20190712152749 on 2019-08-27 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0015_meeting_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='enrollment',
        ),
    ]
